package com.mycompany.thebountyhunter.Rooms;

import com.mycompany.thebountyhunter.Accesso;
import static com.mycompany.thebountyhunter.Commands.*;
import com.mycompany.thebountyhunter.Game;
import com.mycompany.thebountyhunter.ProjectObject;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import static java.lang.String.valueOf;
import java.util.List;
import javax.swing.SwingWorker;
import javax.swing.Timer;


public class CasaArthur extends javax.swing.JFrame {

    WindowListener l = new WindowListener() {
        @Override
        public void windowOpened(WindowEvent arg0) {

            SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {

                @Override
                protected Void doInBackground() throws Exception {
                    this.publish(new String[]{"Benvenuto nella tua piccola casa!"});
                    Thread.sleep(5000);
                    this.publish(new String[]{"C'è un letto e una dispensa a disposizione"});
                    Thread.sleep(5000);
                    this.publish("");
                    CasaArthur.this.lettob.setVisible(true);
                    CasaArthur.this.dispensa.setVisible(true);
                    return null;
                }

                @Override
                protected void process(List<String> res) {
                    res.forEach(thistext -> {
                        text.setText(thistext);
                    });
                }

            };

            worker.execute();

        }

        @Override
        public void windowClosing(WindowEvent arg0) {

        }

        @Override
        public void windowClosed(WindowEvent arg0) {
        }

        @Override
        public void windowIconified(WindowEvent arg0) {

        }

        @Override
        public void windowDeiconified(WindowEvent arg0) {
        }

        @Override
        public void windowActivated(WindowEvent arg0) {
        }

        @Override
        public void windowDeactivated(WindowEvent arg0) {
        }
    };

    /**
     * Creates new form Room3
     */
    public static ProjectObject cibo_dispensa;
    
    boolean aperta = false;
    boolean presente = false;
    int count = 0;

    public CasaArthur() {
        initComponents();
        dispensa.setVisible(false);
        lettob.setVisible(false);
        focaccina_b.setVisible(false);
        mangiab.setVisible(false);
        conservab.setVisible(false);
        uscita.setVisible(false);
        luogo.setText("Casa Arthur");
        this.addWindowListener(l);
        cibo_dispensa = new ProjectObject(4, "Focaccina al mais", "/images/focaccina.png", focaccina_b, this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        satchel = new javax.swing.JButton();
        mangiab = new javax.swing.JButton();
        lettob = new javax.swing.JButton();
        dispensa = new javax.swing.JButton();
        conservab = new javax.swing.JButton();
        focaccina_b = new javax.swing.JButton();
        uscita = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        luogo = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TheBountyHunter");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        satchel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Satchel.png"))); // NOI18N
        satchel.setBorder(null);
        satchel.setBorderPainted(false);
        satchel.setContentAreaFilled(false);
        satchel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        satchel.setFocusPainted(false);
        satchel.setMaximumSize(new java.awt.Dimension(150, 109));
        satchel.setMinimumSize(new java.awt.Dimension(150, 109));
        satchel.setPreferredSize(new java.awt.Dimension(150, 109));
        satchel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satchelActionPerformed(evt);
            }
        });
        getContentPane().add(satchel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 550, -1, -1));

        mangiab.setBackground(new java.awt.Color(255, 0, 51));
        mangiab.setFont(new java.awt.Font("Calibri", 3, 12)); // NOI18N
        mangiab.setText("Mangia");
        mangiab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangiabActionPerformed(evt);
            }
        });
        getContentPane().add(mangiab, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 310, 80, 20));

        lettob.setBorder(null);
        lettob.setBorderPainted(false);
        lettob.setContentAreaFilled(false);
        lettob.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lettob.setFocusPainted(false);
        lettob.setMaximumSize(new java.awt.Dimension(150, 109));
        lettob.setMinimumSize(new java.awt.Dimension(150, 109));
        lettob.setPreferredSize(new java.awt.Dimension(150, 109));
        lettob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lettobActionPerformed(evt);
            }
        });
        getContentPane().add(lettob, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));

        dispensa.setBorderPainted(false);
        dispensa.setContentAreaFilled(false);
        dispensa.setFocusPainted(false);
        dispensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispensaActionPerformed(evt);
            }
        });
        getContentPane().add(dispensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 150, 110));

        conservab.setBackground(new java.awt.Color(255, 0, 51));
        conservab.setFont(new java.awt.Font("Calibri", 3, 12)); // NOI18N
        conservab.setText("Conserva");
        conservab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conservabActionPerformed(evt);
            }
        });
        getContentPane().add(conservab, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 310, 80, 20));

        focaccina_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/focaccina.png"))); // NOI18N
        focaccina_b.setBorderPainted(false);
        focaccina_b.setContentAreaFilled(false);
        focaccina_b.setFocusPainted(false);
        focaccina_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                focaccina_bActionPerformed(evt);
            }
        });
        getContentPane().add(focaccina_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 350, 60, 40));

        uscita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uscita.png"))); // NOI18N
        uscita.setBorderPainted(false);
        uscita.setContentAreaFilled(false);
        uscita.setPreferredSize(new java.awt.Dimension(100, 40));
        uscita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uscitaActionPerformed(evt);
            }
        });
        getContentPane().add(uscita, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        menu.setBackground(new java.awt.Color(255, 51, 0));
        menu.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        menu.setText("MENU DI GIOCO");
        menu.setBorderPainted(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 160, 50));

        luogo.setBackground(new java.awt.Color(0, 0, 0));
        luogo.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        luogo.setForeground(new java.awt.Color(255, 255, 255));
        luogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        luogo.setOpaque(true);
        getContentPane().add(luogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 90));

        text.setBackground(new java.awt.Color(0, 0, 0));
        text.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setOpaque(true);
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1280, 40));

        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/casa.png"))); // NOI18N
        getContentPane().add(sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void satchelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satchelActionPerformed
          openInventory();

    }//GEN-LAST:event_satchelActionPerformed

    private void focaccina_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_focaccina_bActionPerformed
        // TODO add your handling code here:
        focaccina_b.setVisible(true);
        text.setText("La focaccina al mais è tipica del far west, economica e veloce da preparare.");
        Timer timer = new Timer(5000, event -> {
            text.setText("");
        });
        timer.setRepeats(false);
        timer.start();
        this.mangiab.setVisible(true);
        this.conservab.setVisible(true);
    }//GEN-LAST:event_focaccina_bActionPerformed

    private void mangiabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangiabActionPerformed

        focaccina_b.setVisible(false);
        conservab.setVisible(false);
        mangiab.setVisible(false);
    }//GEN-LAST:event_mangiabActionPerformed

    private void conservabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conservabActionPerformed

        PickObject(cibo_dispensa);
        Accesso.p.list.add(CasaArthur.cibo_dispensa.getId());
        mangiab.setVisible(false);
        conservab.setVisible(false);
        focaccina_b.setVisible(false);
    }//GEN-LAST:event_conservabActionPerformed

    private void lettobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lettobActionPerformed

        this.lettob.setVisible(false);
        this.uscita.setVisible(true);
        goScene(this);
    }//GEN-LAST:event_lettobActionPerformed

    private void dispensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispensaActionPerformed

        if (aperta == false) {
            focaccina_b.setVisible(true);
            aperta = true;
        } else {
            text.setText("Nella dispensa non c'è altro.");
            Timer timer = new Timer(5000, event -> {
                text.setText("");
            });
            timer.setRepeats(false);
            timer.start();
        }
    }//GEN-LAST:event_dispensaActionPerformed

    private void uscitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uscitaActionPerformed
        int newid = Game.giornocasa.getId();
        Accesso.p.setRoom(newid);
        MenuUscita.idroom.setText("Room: " + valueOf(newid));
        goSouth(this);
    }//GEN-LAST:event_uscitaActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        MenuUscita.salva.setVisible(false);
        openMenu();

    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CasaArthur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CasaArthur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CasaArthur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CasaArthur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasaArthur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conservab;
    private javax.swing.JButton dispensa;
    private javax.swing.JButton focaccina_b;
    private javax.swing.JButton lettob;
    private javax.swing.JLabel luogo;
    private javax.swing.JButton mangiab;
    private javax.swing.JButton menu;
    private javax.swing.JButton satchel;
    public javax.swing.JLabel sfondo;
    public javax.swing.JLabel text;
    public javax.swing.JButton uscita;
    // End of variables declaration//GEN-END:variables


}
