/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.thebountyhunter.Rooms;

import com.mycompany.thebountyhunter.Accesso;
import static com.mycompany.thebountyhunter.Commands.PickObject;
import static com.mycompany.thebountyhunter.Inventory.findObject;
import com.mycompany.thebountyhunter.ProjectObject;
import java.awt.Dimension;
import static java.lang.String.valueOf;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class CatalogoMarket extends javax.swing.JFrame {

    public static ProjectObject mangime, carne, pesce;

    public CatalogoMarket() {
        initComponents();
        Dimension menuWindow = new Dimension(460, 360);
        this.setLocationRelativeTo(null);
        this.setSize(menuWindow);
        this.setResizable(false);
        mangime = new ProjectObject(5, "mangime cavallo", "/images/mangime.png", mangimeb, this, 1);
        pesce = new ProjectObject(6, "pesce", "/images/pesce.png", pesceb, this, 1);
        carne = new ProjectObject(7, "carne", "/images/carne.png", carneb, this, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesceb = new javax.swing.JButton();
        mangimeb = new javax.swing.JButton();
        carneb = new javax.swing.JButton();
        mangime1 = new javax.swing.JLabel();
        carne1 = new javax.swing.JLabel();
        pesce1 = new javax.swing.JLabel();
        prezzo1 = new javax.swing.JLabel();
        prezzo2 = new javax.swing.JLabel();
        prezzo3 = new javax.swing.JLabel();
        sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Catalogo Market");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pesceb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pesce.png"))); // NOI18N
        pesceb.setBorderPainted(false);
        pesceb.setContentAreaFilled(false);
        pesceb.setFocusPainted(false);
        pesceb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pescebActionPerformed(evt);
            }
        });
        getContentPane().add(pesceb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 120, 70));

        mangimeb.setBackground(new java.awt.Color(255, 255, 255));
        mangimeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mangime.png"))); // NOI18N
        mangimeb.setBorderPainted(false);
        mangimeb.setContentAreaFilled(false);
        mangimeb.setFocusPainted(false);
        mangimeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangimebActionPerformed(evt);
            }
        });
        getContentPane().add(mangimeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 70));

        carneb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carne.png"))); // NOI18N
        carneb.setBorderPainted(false);
        carneb.setContentAreaFilled(false);
        carneb.setFocusPainted(false);
        carneb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carnebActionPerformed(evt);
            }
        });
        getContentPane().add(carneb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 70));

        mangime1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        mangime1.setForeground(new java.awt.Color(255, 255, 0));
        mangime1.setText("CARNE");
        getContentPane().add(mangime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 50, -1));

        carne1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        carne1.setForeground(new java.awt.Color(255, 255, 0));
        carne1.setText("PREZZO: 10 $");
        getContentPane().add(carne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        pesce1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        pesce1.setForeground(new java.awt.Color(255, 255, 0));
        pesce1.setText("MANGIME");
        getContentPane().add(pesce1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        prezzo1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        prezzo1.setForeground(new java.awt.Color(255, 255, 0));
        prezzo1.setText("PESCE");
        getContentPane().add(prezzo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        prezzo2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        prezzo2.setForeground(new java.awt.Color(255, 255, 0));
        prezzo2.setText("PREZZO: 10 $");
        getContentPane().add(prezzo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        prezzo3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        prezzo3.setForeground(new java.awt.Color(255, 255, 0));
        prezzo3.setText("PREZZO: 10 $");
        getContentPane().add(prezzo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/catalogo.jpg"))); // NOI18N
        getContentPane().add(sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mangimebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangimebActionPerformed

        if (findObject(mangime) < 0) {
            if (Accesso.p.getSoldi() >= 10) {
                int saldo = Accesso.p.getSoldi() - 10;
                Accesso.p.setSoldi(saldo);
                MenuUscita.soldigiocatore.setText("Soldi: $" + valueOf(Accesso.p.getSoldi()));
                PickObject(mangime);
                Accesso.p.getList().add(mangime.getId());
                JOptionPane.showMessageDialog(this, "Hai comprato il mangime per il tuo cavallo", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Non hai abbastanza soldi", "errore", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hai già il mangime per il tuo cavallo", "errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mangimebActionPerformed

    private void carnebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carnebActionPerformed

        if (findObject(carne) < 0) {
            if (Accesso.p.getSoldi() >= 10) {
                int saldo = Accesso.p.getSoldi() - 10;
                Accesso.p.setSoldi(saldo);
                MenuUscita.soldigiocatore.setText("Soldi: $" + valueOf(Accesso.p.getSoldi()));
                PickObject(carne);
                Accesso.p.getList().add(carne.getId());
                JOptionPane.showMessageDialog(this, "Hai comprato la carne", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Non hai abbastanza soldi", "errore", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hai già carne per te", "errore", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_carnebActionPerformed

    private void pescebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pescebActionPerformed

        if (findObject(pesce) < 0) {
            if (Accesso.p.getSoldi() >= 10) {
                int saldo = Accesso.p.getSoldi() - 10;
                Accesso.p.setSoldi(saldo);
                MenuUscita.soldigiocatore.setText("Soldi: $" + valueOf(Accesso.p.getSoldi()));
                PickObject(pesce);
                Accesso.p.getList().add(pesce.getId());
                JOptionPane.showMessageDialog(this, "Hai comprato il pesce", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Non hai abbastanza soldi", "errore", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hai già pesce per te", "errore", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_pescebActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoMarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoMarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoMarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoMarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogoMarket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carne1;
    private javax.swing.JButton carneb;
    private javax.swing.JLabel mangime1;
    private javax.swing.JButton mangimeb;
    private javax.swing.JLabel pesce1;
    private javax.swing.JButton pesceb;
    private javax.swing.JLabel prezzo1;
    private javax.swing.JLabel prezzo2;
    private javax.swing.JLabel prezzo3;
    private javax.swing.JLabel sfondo;
    // End of variables declaration//GEN-END:variables

    public void setCatalogoForm(JFrame catalogo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
