/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.thebountyhunter.Rooms;

import com.mycompany.thebountyhunter.Accesso;
import static com.mycompany.thebountyhunter.Commands.PickObject;
import static com.mycompany.thebountyhunter.Inventory.findObject;
import com.mycompany.thebountyhunter.ProjectObject;
import java.awt.Dimension;
import static java.lang.String.valueOf;
import javax.swing.JOptionPane;


public class CatalogoArmeria extends javax.swing.JFrame {

    public static ProjectObject cecchino, pompa, ascia;
    
    public CatalogoArmeria() {
        initComponents();
        Dimension menuWindow = new Dimension(460, 360);
        this.setLocationRelativeTo(null);
        this.setSize(menuWindow);
        this.setResizable(false);
        cecchino = new ProjectObject(8, "cecchino", "/images/cecchino.png", cecchinob, this, 1);
        pompa = new ProjectObject(9, "fucile a pompa", "/images/pompa.png", pompab, this, 1);
        ascia = new ProjectObject(10, "ascia", "/images/ascia.png", asciab, this, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prezzo1 = new javax.swing.JLabel();
        prezzo2 = new javax.swing.JLabel();
        prezzo3 = new javax.swing.JLabel();
        cecchino1 = new javax.swing.JLabel();
        pompa1 = new javax.swing.JLabel();
        ascia1 = new javax.swing.JLabel();
        consiglio = new javax.swing.JLabel();
        pompab = new javax.swing.JButton();
        cecchinob = new javax.swing.JButton();
        asciab = new javax.swing.JButton();
        sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Catalogo Armeria");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prezzo1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        prezzo1.setForeground(new java.awt.Color(255, 255, 0));
        prezzo1.setText("PREZZO: 350 $");
        getContentPane().add(prezzo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        prezzo2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        prezzo2.setForeground(new java.awt.Color(255, 255, 0));
        prezzo2.setText("PREZZO: 200 $");
        getContentPane().add(prezzo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        prezzo3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        prezzo3.setForeground(new java.awt.Color(255, 255, 0));
        prezzo3.setText("PREZZO: 100 $");
        getContentPane().add(prezzo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        cecchino1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cecchino1.setForeground(new java.awt.Color(255, 255, 0));
        cecchino1.setText("CECCHINO");
        getContentPane().add(cecchino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        pompa1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        pompa1.setForeground(new java.awt.Color(255, 255, 0));
        pompa1.setText("FUCILE A POMPA");
        getContentPane().add(pompa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        ascia1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ascia1.setForeground(new java.awt.Color(255, 255, 0));
        ascia1.setText("ASCIA DA COMBATTIMENTO");
        getContentPane().add(ascia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        consiglio.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        consiglio.setForeground(new java.awt.Color(255, 255, 255));
        consiglio.setText("POTREBBE ESSERE MOLTO EFFICACE");
        getContentPane().add(consiglio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 230, -1));

        pompab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pompa.png"))); // NOI18N
        pompab.setBorderPainted(false);
        pompab.setContentAreaFilled(false);
        pompab.setFocusPainted(false);
        pompab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pompabActionPerformed(evt);
            }
        });
        getContentPane().add(pompab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, 70));

        cecchinob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cecchino.png"))); // NOI18N
        cecchinob.setBorderPainted(false);
        cecchinob.setContentAreaFilled(false);
        cecchinob.setFocusPainted(false);
        cecchinob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cecchinobActionPerformed(evt);
            }
        });
        getContentPane().add(cecchinob, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 70));

        asciab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ascia.png"))); // NOI18N
        asciab.setBorderPainted(false);
        asciab.setContentAreaFilled(false);
        asciab.setFocusPainted(false);
        asciab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asciabActionPerformed(evt);
            }
        });
        getContentPane().add(asciab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, 70));

        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/catalogo.jpg"))); // NOI18N
        getContentPane().add(sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cecchinobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cecchinobActionPerformed
        if (findObject(cecchino) < 0) {
            if (Accesso.p.getSoldi() >= 350) {
                int saldo = Accesso.p.getSoldi() - 350;
                Accesso.p.setSoldi(saldo);
                MenuUscita.soldigiocatore.setText("Soldi: $" + valueOf(Accesso.p.getSoldi()));
                PickObject(cecchino);
                Accesso.p.list.add(cecchino.getId());
                JOptionPane.showMessageDialog(this, "Hai comprato un fucile di precisione", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Non hai abbastanza soldi", "errore", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hai già il cecchino", "errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cecchinobActionPerformed

    private void pompabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pompabActionPerformed
        if (findObject(pompa) < 0) {
            if (Accesso.p.getSoldi() >= 200) {
                int saldo = Accesso.p.getSoldi() - 200;
                Accesso.p.setSoldi(saldo);
                MenuUscita.soldigiocatore.setText("Soldi: $" + valueOf(Accesso.p.getSoldi()));
                PickObject(pompa);
                Accesso.p.list.add(pompa.getId());
                JOptionPane.showMessageDialog(this, "Hai comprato un fucile a pompa", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Non hai abbastanza soldi", "errore", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hai già il fucile a pompa", "errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pompabActionPerformed

    private void asciabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asciabActionPerformed
        if (findObject(ascia) < 0) {
            if (Accesso.p.getSoldi() >= 100) {
                int saldo = Accesso.p.getSoldi() - 100;
                Accesso.p.setSoldi(saldo);
                MenuUscita.soldigiocatore.setText("Soldi: $" + valueOf(Accesso.p.getSoldi()));
                PickObject(ascia);
                Accesso.p.list.add(ascia.getId());
                JOptionPane.showMessageDialog(this, "Hai comprato un'ascia da combattimento", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Non hai abbastanza soldi", "errore", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hai già un'ascia da combattimento", "errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_asciabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoArmeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoArmeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoArmeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoArmeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogoArmeria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ascia1;
    private javax.swing.JButton asciab;
    private javax.swing.JLabel cecchino1;
    private javax.swing.JButton cecchinob;
    private javax.swing.JLabel consiglio;
    private javax.swing.JLabel pompa1;
    private javax.swing.JButton pompab;
    private javax.swing.JLabel prezzo1;
    private javax.swing.JLabel prezzo2;
    private javax.swing.JLabel prezzo3;
    public javax.swing.JLabel sfondo;
    // End of variables declaration//GEN-END:variables
}
