/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.thebountyhunter.Rooms;

import com.mycompany.thebountyhunter.Accesso;
import com.mycompany.thebountyhunter.Progresso;
import java.awt.Dimension;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import static java.lang.String.valueOf;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class MenuUscita extends javax.swing.JFrame {

   
    private static Progresso p;

    public MenuUscita(Progresso p) {
        initComponents();
        this.p = p;
        Dimension menuWindow = new Dimension(749, 422);
        this.setLocationRelativeTo(null);
        this.setSize(menuWindow);
        this.setResizable(false);
        username.setText("Username: " + Accesso.testousername.getText());
        soldigiocatore.setText("Soldi: $" + valueOf(Accesso.p.getSoldi()));
        idroom.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        continua = new javax.swing.JButton();
        salva = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        soldigiocatore = new javax.swing.JLabel();
        idroom = new javax.swing.JLabel();
        sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        continua.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        continua.setForeground(new java.awt.Color(240, 240, 240));
        continua.setText("CONTINUA");
        continua.setBorderPainted(false);
        continua.setContentAreaFilled(false);
        continua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuaActionPerformed(evt);
            }
        });
        getContentPane().add(continua, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 150, -1));

        salva.setBackground(new java.awt.Color(255, 0, 0));
        salva.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        salva.setForeground(new java.awt.Color(255, 255, 255));
        salva.setText("SALVA ");
        salva.setBorderPainted(false);
        salva.setContentAreaFilled(false);
        salva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaActionPerformed(evt);
            }
        });
        getContentPane().add(salva, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 190, -1));

        username.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 340, 30));

        soldigiocatore.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        soldigiocatore.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(soldigiocatore, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, 30));

        idroom.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        idroom.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(idroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 0, -1));

        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuExit.jpg"))); // NOI18N
        getContentPane().add(sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuaActionPerformed
        dispose();
    }//GEN-LAST:event_continuaActionPerformed

    private void salvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaActionPerformed

        FileOutputStream fos = null;
        try {
            fos = new FileOutputStream("salvataggi/" + p.getNome() + ".dat");
            ObjectOutputStream salvaObj = new ObjectOutputStream(fos);
            salvaObj.writeObject(p);
            salvaObj.flush();
            fos.close();
            JOptionPane.showMessageDialog(this, "Partita salvata correttamente", "Info", JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException e1) {
            System.out.println("Non riesco a aprire il file in scrittura");
        } catch (IOException e2) {
            System.out.println("Non riesco a aprire il file in scrittura");
        }

    }//GEN-LAST:event_salvaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUscita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUscita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUscita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUscita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuUscita(p).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continua;
    public static javax.swing.JLabel idroom;
    public static javax.swing.JButton salva;
    public javax.swing.JLabel sfondo;
    public static javax.swing.JLabel soldigiocatore;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

    public void setMenuform(JFrame menu) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
