/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.thebountyhunter.Rooms;

import static com.mycompany.thebountyhunter.Commands.*;
import static com.mycompany.thebountyhunter.Inventory.*;
import javax.swing.JOptionPane;

public class SceltaUccisione extends javax.swing.JFrame {

    public SceltaUccisione() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scelta = new javax.swing.JLabel();
        stealth = new javax.swing.JButton();
        distanza = new javax.swing.JButton();
        sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TheBountyHunter");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scelta.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        scelta.setForeground(new java.awt.Color(255, 255, 0));
        scelta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scelta.setText("SCEGLI COME UCCIDERE BRONTE");
        getContentPane().add(scelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 450, 50));

        stealth.setBackground(new java.awt.Color(255, 255, 0));
        stealth.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        stealth.setText("UCCISIONE STEALTH");
        stealth.setBorderPainted(false);
        stealth.setFocusPainted(false);
        stealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stealthActionPerformed(evt);
            }
        });
        getContentPane().add(stealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 220, 80));

        distanza.setBackground(new java.awt.Color(255, 255, 0));
        distanza.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        distanza.setText("UCCISIONE A DISTANZA");
        distanza.setBorderPainted(false);
        distanza.setFocusPainted(false);
        distanza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanzaActionPerformed(evt);
            }
        });
        getContentPane().add(distanza, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 220, 80));

        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scelta.png"))); // NOI18N
        getContentPane().add(sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void distanzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanzaActionPerformed
        if (findObject(CatalogoArmeria.cecchino) >= 0) {
            goScene(this);
        } else {
            JOptionPane.showMessageDialog(this, "Non hai il cecchino per poter uccidere a distanza", "Scelta impossibile", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_distanzaActionPerformed

    private void stealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stealthActionPerformed
        goRoom(this);
    }//GEN-LAST:event_stealthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SceltaUccisione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SceltaUccisione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SceltaUccisione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SceltaUccisione.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SceltaUccisione().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton distanza;
    private javax.swing.JLabel scelta;
    public javax.swing.JLabel sfondo;
    private javax.swing.JButton stealth;
    // End of variables declaration//GEN-END:variables
}
