/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.thebountyhunter.Rooms;

import com.mycompany.thebountyhunter.Accesso;
import static com.mycompany.thebountyhunter.Commands.*;
import com.mycompany.thebountyhunter.ProjectObject;

public class SceltaRevolver extends javax.swing.JFrame {

    public static ProjectObject cattleman, magnum, heavy;

    public SceltaRevolver() {
        initComponents();
        cattleman = new ProjectObject(0, "Cattleman revolver", "/images/revolver1.png", revolver1, this);
        magnum = new ProjectObject(1, ".44 Magnum", "/images/revolver2.png", revolver2, this);
        heavy = new ProjectObject(2, "Heavy revolver", "/imges/revolver3.png", revolver3, this);
        continua.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        continua = new javax.swing.JButton();
        revolver2 = new javax.swing.JButton();
        revolver1 = new javax.swing.JButton();
        revolver3 = new javax.swing.JButton();
        sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TheBountyHunter");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCEGLI LA TUA REVOLVER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 450, 50));

        continua.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        continua.setForeground(new java.awt.Color(255, 255, 0));
        continua.setText("CONTINUA");
        continua.setBorderPainted(false);
        continua.setContentAreaFilled(false);
        continua.setFocusPainted(false);
        continua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuaActionPerformed(evt);
            }
        });
        getContentPane().add(continua, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 420, 50));

        revolver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/revolver2.png"))); // NOI18N
        revolver2.setBorderPainted(false);
        revolver2.setContentAreaFilled(false);
        revolver2.setFocusPainted(false);
        revolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revolver2ActionPerformed(evt);
            }
        });
        getContentPane().add(revolver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 250, 160));

        revolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/revolver1.png"))); // NOI18N
        revolver1.setBorderPainted(false);
        revolver1.setContentAreaFilled(false);
        revolver1.setFocusPainted(false);
        revolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revolver1ActionPerformed(evt);
            }
        });
        getContentPane().add(revolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 250, 160));

        revolver3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/revolver3.png"))); // NOI18N
        revolver3.setBorderPainted(false);
        revolver3.setContentAreaFilled(false);
        revolver3.setFocusPainted(false);
        revolver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revolver3ActionPerformed(evt);
            }
        });
        getContentPane().add(revolver3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, 250, 160));

        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scelta.png"))); // NOI18N
        getContentPane().add(sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void revolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revolver1ActionPerformed
        PickObject(cattleman);
        Accesso.p.list.add(SceltaRevolver.cattleman.getId());
        revolver2.setVisible(false);
        revolver3.setVisible(false);
        continua.setVisible(true);

    }//GEN-LAST:event_revolver1ActionPerformed

    private void revolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revolver2ActionPerformed
        PickObject(magnum);
        Accesso.p.list.add(SceltaRevolver.magnum.getId());
        revolver1.setVisible(false);
        revolver3.setVisible(false);
        continua.setVisible(true);

    }//GEN-LAST:event_revolver2ActionPerformed

    private void revolver3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revolver3ActionPerformed
        PickObject(heavy);
        Accesso.p.list.add(SceltaRevolver.heavy.getId());
        revolver1.setVisible(false);
        revolver2.setVisible(false);
        continua.setVisible(true);

    }//GEN-LAST:event_revolver3ActionPerformed

    private void continuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuaActionPerformed
       goScene(this);
    }//GEN-LAST:event_continuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SceltaRevolver.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SceltaRevolver.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SceltaRevolver.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SceltaRevolver.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SceltaRevolver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton revolver1;
    private javax.swing.JButton revolver2;
    private javax.swing.JButton revolver3;
    public javax.swing.JLabel sfondo;
    // End of variables declaration//GEN-END:variables
}
