/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.thebountyhunter.Rooms;

import static com.mycompany.thebountyhunter.Commands.*;

public class ScenaCecchino extends javax.swing.JFrame {

    int sparo = 0;
    
    
    public ScenaCecchino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spara = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        proiettile1 = new javax.swing.JButton();
        proiettile2 = new javax.swing.JButton();
        proiettile3 = new javax.swing.JButton();
        sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TheBountyHunter");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spara.setBackground(new java.awt.Color(255, 51, 0));
        spara.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        spara.setText("SPARA BRONTE");
        spara.setBorderPainted(false);
        spara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sparaActionPerformed(evt);
            }
        });
        getContentPane().add(spara, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 490, 170, 40));

        menu.setBackground(new java.awt.Color(255, 51, 0));
        menu.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        menu.setText("MENU DI GIOCO");
        menu.setBorderPainted(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 160, 50));

        proiettile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/proiettile.png"))); // NOI18N
        proiettile1.setBorderPainted(false);
        proiettile1.setContentAreaFilled(false);
        proiettile1.setFocusPainted(false);
        getContentPane().add(proiettile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 630, 150, 40));

        proiettile2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/proiettile.png"))); // NOI18N
        proiettile2.setBorderPainted(false);
        proiettile2.setContentAreaFilled(false);
        proiettile2.setFocusPainted(false);
        getContentPane().add(proiettile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 590, 150, 40));

        proiettile3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/proiettile.png"))); // NOI18N
        proiettile3.setBorderPainted(false);
        proiettile3.setContentAreaFilled(false);
        proiettile3.setFocusPainted(false);
        getContentPane().add(proiettile3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 550, 150, 40));

        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scenacecchino.jpg"))); // NOI18N
        getContentPane().add(sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sparaActionPerformed
        switch (sparo) {
            case 0:
                proiettile1.setVisible(false);
                sparo += 1;
                break;
            case 1:
                proiettile2.setVisible(false);
                sparo += 1;
                break;
            default:
                goScene(this);
                break;
        }
    }//GEN-LAST:event_sparaActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        MenuUscita.salva.setVisible(false);
        openMenu();
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScenaCecchino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScenaCecchino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScenaCecchino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScenaCecchino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScenaCecchino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton menu;
    private javax.swing.JButton proiettile1;
    private javax.swing.JButton proiettile2;
    private javax.swing.JButton proiettile3;
    public javax.swing.JLabel sfondo;
    private javax.swing.JButton spara;
    // End of variables declaration//GEN-END:variables
}
